package com.management.system.models;

import jakarta.persistence.*;


@Entity
@Table(name="Book")
public class BookModel {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(unique = true, nullable=false)
	private Long id;//unique, autogenerated, pk
	@Column(nullable=false, length=100)
	private String title;//not null
	@Column(nullable=false, length=100)
	private String author;//not null
	@Column(unique=true, length=13)
	private String isbn; //unique
	@Column(nullable=false)
	private Integer publishedYear;
	@Column(nullable=false, columnDefinition = "BOOLEAN DEFAULT TRUE") 
	private Boolean available=true;//default true
	
	public BookModel() {} //jpa

	public BookModel(Long id, String title, String author, String isbn, Integer publishedYear, boolean available) {
		
		this.id = id;
		this.title = title;
		this.author = author;
		this.isbn = isbn;
		this.publishedYear = publishedYear;
		this.available = available;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public Integer getPublishedYear() {
		return publishedYear;
	}

	public void setPublishedYear(Integer publishedYear) {
		this.publishedYear = publishedYear;
	}

	public boolean isAvailable() {
		return available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}
	
	
	
}
